Description: Git Sync
Parameters:
  BucketTag:
    Description: Tag Val of S3
    Type: String
    Default: "Hello World"
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-bucket-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: "Application"
          Value: "Git Demo"
        - Key: "Dynamic Tag"
          Value: !Ref BucketTag
  AnotherBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-anotherbucket-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: "Application"
          Value: "Git Demo2"
        - Key: "Dynamic Tag"
          Value: !Ref AnotherBucketTag

        

        
